### ISSUE TITLE
EffectiveMobile

### ISSUE THREAD

**Issue by Izumra** [blazee5/EffectiveMobile_test#1]
Привет, прошел собеседование?

**Comment by blazee5** [comment]
привет, нет

**Comment by Izumra** [comment]
А оно было вообще. Мне не отвечает контора.

**Comment by blazee5** [comment]
было неделю назад

**Comment by Izumra** [comment]
Я видел, твой проект, сильно написан, как они не взяли? HR не понравился? Что вообще на собеседовании было

**Comment by blazee5** [comment]
тестовое понравилось, но собес сложный был, я не на все ответил, сказали нашли другого сильнее
